{% set name = "sphinxcontrib-httpexample" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b75163c9da5d551858133f32a89c260c16e4ae8fa3f4be69a31bc9e182e1bb7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - astunparse
    - docutils
    - sphinx
    - sphinxcontrib-httpdomain

test:
  imports:
    - sphinxcontrib

about:
  home: https://github.com/collective/sphinxcontrib-httpexample
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Adds example directive for sphinx-contrib httpdomain.'
  description: |
    sphinxcontrib-httpexample enhances sphinxcontrib-httpdomain, a Sphinx domain
    extension for describing RESTful HTTP APIs in detail, with a simple call
    example directive. The new directive provided by this extension generates
    RESTful HTTP API call examples for different tools from a single HTTP
    request example.
  doc_url: http://sphinxcontrib-httpexample.readthedocs.io/
  dev_url: https://github.com/collective/sphinxcontrib-httpexample

extra:
  recipe-maintainers:
    - carlodri
