travis:
  secure:
    BINSTAR_TOKEN: YIJxTmAGtHJDiSlSwkvBZTYz32o1bGME1vyaXaYxEOR7QUjz6XKwt96+MBIN983VDHb8GhFaTakIW8D+QAFFwRNxGh/HHLDKMtaLaIt6VwztMHxyJ88ulHxK8Xuh8Z2INg1lv4FQwv6vG5XCPZu+LKz7yaoVcxP2oBzgRbhzCKq/LT2D/b2ke6DaN/nXK8gARfyoxB4s59Q+QcHsOlJP82dT1aKtdJI2/BXMmSaHqcPwzUnyHcgFvdtuURR1Hpr1EuhYbGGcbfe2uYbC0X8oC4YMoeoLxpnIfFJSQP4JosrAx6WYcr8/qxv9DxYkQYAkSfTGPgzFJuJ63icCnE/A5ilhMmvt1LAyb1ftLpzk/TcC5VY+wvDhVk/nFAXKvxmSjc6cMqj2OJN02JTHznv61yvfDh47M1E2l7qe4ao0rAXfwM8Cz1705yLYBTKrZns07V4m4UBUS0NlCuRfvhmVyyryTjrxkywQAEjUL1GlbiKmv/5NNayMKmJ8/ePqYQs78/Fj5fgv9fO3YusOM/2CzbyB1Byv/kiDmLYp5Mk3utbBpErEnbSqg55ZXre3Ubb6qpx3iRrVUzJZL5xQdNuYGFpkAut2GzhNx2i5vHL1arYSv9JKrqYSyo6V8rzYuuZcybKx18rPVJZAdVow8C27K3vtcbDuyHdADgRjImdcRjo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
